apiVersion: v1
kind: Pod
metadata:
  name: netpod1
  labels:
    app: netpod
    podkey: netpodkey1
spec:
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 10
  containers:
  - name: netctr
    image: mizarnet/testpod
    ports:
    - containerPort: 9001
      protocol: TCP
    - containerPort: 5001
      protocol: UDP
    - containerPort: 7000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: netpod2
  labels:
    app: netpod
spec:
  affinity:
    podAntiAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: podkey
            operator: In
            values:
            - netpodkey1
        topologyKey: kubernetes.io/hostname
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 10
  containers:
  - name: netctr
    image: mizarnet/testpod
    ports:
    - containerPort: 9001
      protocol: TCP
    - containerPort: 5001
      protocol: UDP
    - containerPort: 7000
      protocol: TCP
---
apiVersion: v1
kind: Pod
metadata:
  name: netpod3
  labels:
    app: netpod
spec:
  affinity:
    podAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
      - labelSelector:
          matchExpressions:
          - key: podkey
            operator: In
            values:
            - netpodkey1
        topologyKey: kubernetes.io/hostname
  restartPolicy: OnFailure
  terminationGracePeriodSeconds: 10
  containers:
  - name: netctr
    image: mizarnet/testpod
    ports:
    - containerPort: 9001
      protocol: TCP
    - containerPort: 5001
      protocol: UDP
    - containerPort: 7000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: netsvc
spec:
  selector:
    app: netpod
  ports:
    - name: tcpapp
      protocol: TCP
      port: 9001
      targetPort: 9001
    - name: udpapp
      protocol: UDP
      port: 5001
      targetPort: 5001
    - name: httpapp
      protocol: TCP
      port: 7000
      targetPort: 7000
